name: Deploy to Portainer
description: Deploys Docker Compose files to a Portainer instance.
author: Your Name

branding:
  icon: upload-cloud
  color: blue

inputs:
  portainer_url:
    description: 'The URL of the Portainer instance'
    required: true
    default: ''
  portainer_api_key:
    description: 'The API key for Portainer authentication'
    required: true
    default: ''
  changed_files_path:
    description: 'Path to the file containing changed Docker Compose files'
    required: true
    default: ''
  environment_file:
    description: 'The environment file to use for the deployment'
    required: false
    default: 'default'

outputs:
  status:
    description: 'Status of the deployment'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.portainer_url }}
    - ${{ inputs.portainer_api_key }}
    - ${{ inputs.changed_files_path }}
    - ${{ inputs.environment_file }}