name: Deploy to Portainer
description: Deploy Docker Compose files to Portainer

inputs:
  portainer_url:
    description: 'The URL of the Portainer instance'
    required: true
    default: ''
  portainer_api_key:
    description: 'The API key for Portainer authentication'
    required: true
    default: ''
  environment_map:
    description: 'A JSON object mapping environment names to IDs'
    required: true
    default: ''
  changed_files_path:
    description: 'Path to the file containing changed Docker Compose files'
    required: true
    default: ''

runs:
  using: 'docker'
  image: 'docker://your_docker_image'
  args:
    - ${{ inputs.portainer_url }}
    - ${{ inputs.portainer_api_key }}
    - ${{ inputs.environment_map }}
    - ${{ inputs.changed_files_path }}
